exclude:
  - README.md
  - /*.pdn
  - /*.xcf
  - /Thumbs.db

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

permalink: '/blog/posts/:year/:month/:day/:title.html'
paginate: 5
paginate_path: "/?page=:num"
url: 'http://www.jm-org.net'

comments: true
vk-support: true
